swagger: '2.0'
info:
  title: Account Aggregator API - Portability
  description: |-
    # Summary

     This is portability Api for AA. This helps to port the accounts and consents across AA.
      

    ---
  version: 1.1.1
  contact:
    email: aa-api@rebit.org.in
tags:
  - name: Portability Flow
    description: Account and Consent Portability APIs
schemes:
  - https
securityDefinitions:
  Client_api_key:
    type: apiKey
    name: client_api_key
    in: header
  FIP_api_key:
    type: apiKey
    name: fip_api_key
    in: header
security:
  - Client_api_key: []
consumes:
  - application/json
produces:
  - application/json
paths:
  /Port:
    post:
      tags:
        - Portability Flow
      description: >-
        This API is intended for AA to port the linked Accounts and Consent Artefacts from other AA.


        <br>Note: "Request Body Example Value" and "Responses Example Value"
        given below is for illustrative purposes only.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AAPortRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AAPortResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  '/Port/{RefNumber}/{Token}':
   get:
      tags:
        - Portability Flow
      description: >-
        This API is used to validate the user while porting the accounts & Consents from another AA.

         <br>Note: "Request Body Example Value" and "Responses Example Value" given below is for illustrative purposes only.
      parameters:
        - name: RefNumber
          in: path
          description: >-
            The reference number that was generated by the AA in response to an
            accounts and consent port request. The current API enables completion of account
            port for the specified AA id in that request.
          required: true
          type: string
        - name: Token
          in: path
          description: >-
            The token that was sent to the customer by the AA to confirm
            account port activity
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PortAccountsTokenResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
definitions:
  AAPortRequest:
    type: object
    required:
      - ver
      - timestamp
      - txnid
      - Customer
    properties:
      ver:
        type: string
        example: '1.0'
        description: Version of the NBFC-AA Ecosystem API
        xml:
          attribute: true
      timestamp:
        type: string
        description: Current timestamp
        format: date-time
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          An unique transaction identifier used for providing an end to end
          traceability.
        example: f35761ac-4a18-11e8-96ff-0277a9fbfedc
        xml:
          attribute: true
      Customer:
        type: object
        required:
          - fromAAid
          - aaid
        description: >-
          This block would contain the information about the customer including
          the AA id of current AA and from AA where accounts to be ported.
        properties:
          aaid:
            type: string
            example: AA_001
            description: The unique AA id from where porting request orginated.
            xml:
              attribute: true
          fromAAid:
            type: string
            example: customer_identifier@AA_identifier
            description: The unique customer address with the AA from where Accounts to be ported.
            xml:
              attribute: true
  AAPortResponse:
    type: object
    required:
      - ver
      - timestamp
      - txnid
      - RefNumber
    properties:
      ver:
        type: string
        description: The version of the API
        example: '1.0'
        xml:
          attribute: true
      timestamp:
        type: string
        description: Creation timestamp of the message which will be updated at each call
        format: date-time
        example: '2018-09-22T06:13:30.967+0000'
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          An unique transaction identifier used for providing an end to end
          traceability.
        example: f35761ac-4a18-11e8-96ff-0277a9fbfedc
        xml:
          attribute: true
      RefNumber:
        type: string
        description: A UUID string to coorelate the ACCOUNTS-LINKED notification
        example: f6b1482e-8f08-11e8-862a-02552b0d3c36
  PortAccountsTokenResponse:
    description: >-
      A response of confirmation for accounts port with a reference number
      for future identification
    type: object
    required:
      - ver
      - timestamp
      - txnid
      - customerAddress
      - PortAccountDetails
      - ConsentArtefacts
    properties:
      ver:
        type: string
        example: '1.0'
        description: The version of the API
        xml:
          attribute: true
      timestamp:
        type: string
        description: Creation timestamp of the message which will be updated at each call
        format: date-time
        example: '2018-05-05T10:27:17.699+0000'
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          An unique transaction identifier used for providing an end to end
          traceability.
        example: 410c2d2e-4a1e-11e8-960e-0277a9fbfedc
        xml:
          attribute: true
      customerAddress:
        type: string
        example: 'customer_address@aa_identifier'
        xml:
          attribute: true
      ConsentArtefacts:
        description: A list of ConsentArtefact
        type: array
        items:
          $ref: '#/definitions/ConsentArtefact'
      PortAccountDetails:
        type: array
        items:
          type: object
          required:
            - fipid
            - linkRefNumber
            - accRefNumber
            - status
          properties:
            fipid:
              type: string
              example: FIP_001
              xml:
                attribute: true
            linkRefNumber:
              type: string
              example: xxxxxxxxxxxxx
              xml:
                attribute: true
            accRefNumber:
              type: string
              example: XXXXXXXXXXXX
              xml:
                attribute: true
            status:
              type: string
              example: PORTED
              enum:
                - LINKED
                - DELINKED
                - PORTED
              xml:
                attribute: true
  ConsentArtefact:
    type: object
    required:
      - ver
      - txnid
      - consentId
      - createTimestamp
      - ConsentDetail
      - consentDetailDigitalSignature
      - ConsentUse
      - status
    properties:
      ver:
        type: string
        example: '1.0'
        description: Version of the AA Ecosystem API's
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          The unique transaction identifier used for providing an end to end
          traceability. 
        example: 0b811819-9044-4856-b0ee-8c88035f8858
        xml:
          attribute: true
      consentId:
        type: string
        description: The unique ID of the consent artefact
        example: XXXX-XXXX-XXXX-XXXX
        xml:
          attribute: true
      status:
        type: string
        description: Current Status of the Consent
        enum:
          - ACTIVE
          - PAUSED
          - REVOKED
          - EXPIRED
      createTimestamp:
        type: string
        format: date-time
        example: '2018-12-06T11:39:57.153Z'
        description: Creation time of the consent artefact
        xml:
          attribute: true
      ConsentDetail:
        type: object
        description: >-
          This Section defines the consent and should be digitally signed. CAN
          NOT CHANGE after generation, for any change a new consent has to be
          generated.
        required:
          - consentStart
          - consentExpiry
          - consentMode
          - fetchType
          - consentTypes
          - fiTypes
          - DataConsumer
          - DataProvider
          - Customer
          - Purpose
          - FIDataRange
          - DataLife
          - Frequency
          - Accounts
          - DataFilter
        properties:
          consentStart:
            type: string
            format: date-time
            example: '2019-12-06T11:39:57.153Z'
            description: >-
              Start date-time of the consent. This field would allow for
              Post-Dated consent.
            xml:
              attribute: true
          consentExpiry:
            type: string
            format: date-time
            example: '2019-12-06T11:39:57.153Z'
            description: Expiry date-time for the consent
            xml:
              attribute: true
          consentMode:
            type: string
            description: Consent Mode as defined in the AA Technical Specification
            enum:
              - VIEW
              - STORE
              - QUERY
              - STREAM
            xml:
              attribute: true
          fetchType:
            type: string
            description: FI Fetch type. Could be ONETIME or PERIODIC
            enum:
              - ONETIME
              - PERIODIC
            xml:
              attribute: true
          consentTypes:
            type: array
            minItems: 1
            items:
              type: string
              enum:
                - PROFILE
                - SUMMARY
                - TRANSACTIONS
              example: PROFILE
          fiTypes:
            type: array
            minItems: 1
            items:
              type: string
              description: >-
                List of FITypes used in the Consent. FITypes names should be as
                defined in the AA Technical Specification
              example: DEPOSIT
          DataConsumer:
            type: object
            description: >-
              Dataconsumer ID. For a consent between FIP & AA, Dataconsumer
              would be AA whereas for a consent between FIU/AA Application & AA,
              Dataconsumer would be FIU/AA Application.
            properties:
              id:
                type: string
                description: DataConsumer ID
                example: DC1
                xml:
                  attribute: true
              type:
                type: string
                description: Type of DataConsumer
                enum:
                  - FIU
                  - AA
                example: AA
          DataProvider:
            type: object
            description: >-
              DataProvider ID. For a consent between FIP & AA, DataProvider
              would be FIP whereas for a consent between FIU/AA Application &
              AA, DataProvider would be AA.
            properties:
              id:
                type: string
                description: DataProvider ID
                example: DP1
                xml:
                  attribute: true
              type:
                type: string
                description: Type of DataConsumer
                enum:
                  - FIP
                  - AA
                example: FIP
          Customer:
            type: object
            description: Address of the end customer
            properties:
              id:
                type: string
                description: Customer Address
                example: customer_identifier@AA_identifier
                xml:
                  attribute: true
          Accounts:
            type: array
            description: >-
              List of accounts which the consent would fetch FI from. For a
              consent between FIU & AA, this list could have accounts from
              multiple FIP. For a consent between FIP & AA, only accounts from
              particular FIP must be present in this section.
            items:
              type: object
              properties:
                fiType:
                  type: string
                  description: Type of Financial Information
                  example: DEPOSIT
                  xml:
                    attribute: true
                fipId:
                  type: string
                  description: FIP ID
                  example: FIP1
                  xml:
                    attribute: true
                accType:
                  type: string
                  description: Type of Account
                  example: SAVINGS
                  xml:
                    attribute: true
                linkRefNumber:
                  type: string
                  description: FIP's linkRefNumber as shared by the FIP after linking
                  example: XXXX-XXXX-XXXX
                  xml:
                    attribute: true
                maskedAccNumber:
                  type: string
                  description: Masked account number
                  example: XXXXXXXX4020
                  xml:
                    attribute: true
            xml:
              name: Accounts
          Purpose:
            $ref: '#/definitions/Purpose'
          FIDataRange:
            description: Data Range (Datetime) for the Financial Information Requested
            type: object
            required:
              - from
              - to
            properties:
              from:
                type: string
                format: date-time
                description: Start date for financial information
                xml:
                  attribute: true
                example: '2017-07-13T11:33:34.509Z'
              to:
                type: string
                format: date-time
                description: End date for financial information
                xml:
                  attribute: true
                example: '2018-07-13T11:33:34.509Z'
          DataLife:
            description: >-
              Datalife defines for how long can the FIU/AA Application store the
              data
            type: object
            required:
              - unit
              - value
            properties:
              unit:
                type: string
                description: A unit of how long consumer can store the data.
                xml:
                  attribute: true
                enum:
                  - DAY
                  - MONTH
                  - YEAR
                  - INF
              value:
                type: number
                description: 'Value for the Datalife Unit. If INF, value must be set to 0.'
                xml:
                  attribute: true
          Frequency:
            description: >-
              Frequency of data request. Could be defined in
              HOUR/DAY/MONTH/YEAR.
            type: object
            required:
              - unit
              - value
            properties:
              unit:
                type: string
                description: >-
                  Define the frequency for repeating access of the financial
                  information
                enum:
                  - HOUR
                  - DAY
                  - MONTH
                  - YEAR
                xml:
                  attribute: true
              value:
                type: number
                description: >-
                  Define the value of unit on  how many can consumer can make a
                  request within defined unit of frequency
                xml:
                  attribute: true
            xml:
              name: Frequency
          DataFilter:
            type: array
            description: rules that will be utilized by FIP to filter the data
            items:
              type: object
              required:
                - type
                - operator
                - value
              properties:
                type:
                  type: string
                  description: The condition to filter the data on.
                  enum:
                    - TRANSACTIONTYPE
                    - TRANSACTIONAMOUNT
                  example: TRANSACTIONAMOUNT
                  xml:
                    attribute: true
                operator:
                  type: string
                  description: Operator to filter data by.
                  enum:
                    - '='
                    - '!='
                    - '>'
                    - '<'
                    - '>='
                    - '<='
                  example: '>='
                  xml:
                    attribute: true
                value:
                  type: string
                  description: Value to filter data
                  example: 20000
                  xml:
                    attribute: true
            xml:
              name: DataFilter
      consentDetailDigitalSignature:
        type: string
        format: byte
        description: >-
          Digital Signature of the ConsentDetail Section after generation. The
          receiver has to verify the given signature by generating signature
          from the received ConsentDetail section.
          'https://www.w3.org/TR/xmldsig-core1/'
        example: Signature of AA as defined in W3C standards; Base64 encoded
      ConsentUse:
        type: object
        description: Section defining the parameters for consent tracking
        required:
          - logUri
          - count
          - lastUseDateTime
        properties:
          logUri:
            type: string
            description: Logging; logUri can be any valid URI including an email address
            xml:
              attribute: true
          count:
            type: number
            description: Number of times the consent has been used
            example: 1
            xml:
              attribute: true
          lastUseDateTime:
            type: string
            format: date-time
            description: Consent Last Used Datetime
            example: '2018-12-06T11:39:57.153Z'
            xml:
              attribute: true
    xml:
      name: ConsentArtefact
      namespace: 'http://standards.rebit.org.in/aa'
  Purpose:
    description: Purpose of the consent defined in the AA Technical Specification
    type: object
    required:
      - code
    properties:
      code:
        type: string
        description: 'Purpose Code as defined in the AA Technical Specification '
        example: '101'
        xml:
          attribute: true
      refUri:
        type: string
        description: URL where the purpose is further defined
        example: 'https://api.rebit.org.in/aa/purpose/101.xml'
        xml:
          attribute: true
      text:
        type: string
        description: Textual Description
        example: Wealth management service
        xml:
          attribute: true
      Category:
        properties:
          type:
            type: string
            description: Category name of the Purpose code
            xml:
              attribute: true
  